# Generated by Django 5.1 on 2024-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='size',
            new_name='storages',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='color',
            name='extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='storage',
            name='extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
