# Generated by Django 5.1 on 2024-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_color_productvariant_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
