# Generated by Django 5.1 on 2024-08-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_character_product_maincharactertype_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='value',
            new_name='character_value',
        ),
    ]
