# Generated by Django 5.1 on 2024-08-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_character_value_character_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexitems',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complexitems',
            name='type',
            field=models.CharField(choices=[('vip', 'VIP'), ('standard', 'STANDARD'), ('mini', 'MINI')], default='standard', max_length=8),
        ),
    ]
