# Generated by Django 5.1 on 2024-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_complexitems_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
