# Generated by Django 5.1 on 2024-08-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_productvariant_is_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='commentary',
            new_name='card_itary',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='payment_type',
            new_name='comment_type',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_items',
            new_name='paymentems',
        ),
    ]
