# Generated by Django 5.1 on 2024-08-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_commentary_card_card_itary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_itary',
            new_name='card_it',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='paymentems',
            new_name='payment_items',
        ),
    ]
