# Generated by Django 5.1 on 2024-08-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_rename_card_itary_card_card_it_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_it',
            new_name='card_items',
        ),
    ]
