# Generated by Django 5.1 on 2024-08-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_rename_card_it_card_card_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_items',
        ),
        migrations.RemoveField(
            model_name='card',
            name='payment_items',
        ),
        migrations.AddField(
            model_name='carditems',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_items', to='common.card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_for', to='common.promocode'),
        ),
        migrations.AlterField(
            model_name='carditems',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
